# Generated by Django 5.0.4 on 2024-05-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('SCHOOL_OF_SCIENCE_AND_COMPUTER_STUDIES', 'School Of Science And Computer Studies'), ('SCHOOL_OF_BUSINESS', 'School Of Business'), ('SCHOOL_OF_ENGINEERING', 'School Of Engineering')], max_length=40)),
                ('department', models.CharField(max_length=50)),
                ('student_matric_number', models.CharField(max_length=15)),
                ('pin', models.CharField(default='', max_length=10, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
