# Generated by Django 5.0.4 on 2024-05-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='student_matric_number',
            field=models.CharField(max_length=20),
        ),
    ]
